name: Update steam playtime

on:
  workflow_dispatch:
  push:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Update-steam-playtime
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v3

      - name: Update Gist
        uses: YouEclipse/steam-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 62fa160542e61ac240820bc0b02b5632
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_ID: ${{ secrets.STEAM_ID }}

      - name: Sync Gist to README
        uses: teoxoy/profile-readme-stats@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
